services:
  aoe-clone:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./server.ts
        - action: rebuild
          path: ./index.html
        - action: rebuild
          path: ./poc.html
        - action: rebuild
          path: ./poc-hud.html
        - action: rebuild
          path: ./poc-avaliacao.html
        - action: rebuild
          path: ./poc-personalizacao.html
        - action: rebuild
          path: ./vite.server.config.ts
        - action: rebuild
          path: ./vite.config.ts
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./tsconfig.json
